[package]
name = "genpassrs"
authors = ["Jonathan Villanueva <westwardfishdme@gmail.com>"]
version = "2.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
clap-stdin = "0.7.0"

rand = "0.9.3"

# steganography + image
image = "0.25.10"                                                                  # added for unit-tests
steganography = { path = "./src/modules/steganographic/lib/steganography_update" } # used for actual image embedding

zxcvbn = "3.1.0"
console = "0.16.3"
aes = "0.8.4"
