[package]
name = "genpassrs"
version = "1.0.4"
edition = "2021" #forgot to change the year lol.

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
clap-stdin = "0.5.1"
rand = "0.8.5"
zxcvbn = "3.1.0"
