[package]
name = "genpassrs"
authors = ["Jonathan Villanueva <westwardfishdme@gmail.com>"]
version = "2.0.4-testing"
edition = "2021"

# debugging and benchmarking
[profile.release]
debug = true

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
clap-stdin = "0.7.0"

rand = "0.9.2"
rpassword = "7.3.1"

# [ steganography crates]
stegano = "0.1.1"       # used for padding and encryption
image = "0.25.5"        # required for steganography, and image checking type.
steganography = "1.0.2" # used for actual image embedding

term = "1.0.1"
zxcvbn = "3.1.0"
